Repository HackathonGteam/gteam, pull requests merged in 2022-11, with the labels that each got.

#19 サインアップ機能の修正
  app.py
Labels: Backend

#16 base.login.signup.html追加
  templates/base.html
  templates/login.html
  templates/signup.html
Labels: Frontend

#24 サインアップ機能・ログイン機能の追加実装
  app.py
  models.py
  requirements.txt
  templates/login.html
  templates/signup.html
Labels: Backend

#26 メッセージ機能の実装
  app.py
  models.py
Labels: Backend

#29 html2ファイルとJSファイルを追加
  templates/detail.html
  templates/index.html
  templates/js/scroll-message.js
  templates/login.html
Labels: Frontend

#42 データベースの変更に伴う対応
  app.py
  models.py
  templates/detail.html
  templates/index.html
  templates/signup.html
  util/DB.py
Labels: DB

#43 サインアップ画面とログイン画面の装飾
  app.py
  static/css/base.css
  static/css/registration.css
  static/img/registration.png
  static/js/scroll-message.js
  templates/base.html
  templates/login.html
  templates/signup.html
Labels: Frontend

#48 ホーム画面のレイアウト作成・サインアップ（ログイン）画面のレイアウトの変更
  app.py
  models.py
  static/css/base.css
  static/css/channel.css
  static/css/color.css
  static/css/pagination.css
  static/css/registration.css
  static/css/styles.css
  static/img/chat-dog.png
  static/img/footprint-brown.jpg
  static/img/footprint-red.jpg
  static/img/registration-dog.jpg
  static/img/registration.png
  static/js/paginathing.min.js
  static/js/pagination.js
  templates/base.html
  templates/index.html
  templates/login.html
  templates/signup.html
Labels: Backend, Frontend

#51 ヘッダーとページネーションの修正
  static/css/channel.css
  static/css/color.css
  static/js/pagination.js
Labels: Frontend

#53 Flaskのサーバーの外部への公開
  app.py
Labels: Infra

#68 同意画面のリファクタリング
  static/css/agreement.css
  static/css/styles.css
  templates/agreement.html
Labels: Frontend

#71 チャンネル編集画面の装飾
  static/css/modal.css
  static/css/styles.css
  templates/modal/update-channel.html
Labels: Frontend

#76 チャンネル名の編集時に既に存在するチャンネル名を送信するとエラーになる問題の解決
  app.py
  models.py
  static/js/update-channel.js
  templates/detail.html
Labels: Backend, Frontend
